### ISSUE TITLE
Web site stoped syncing

### ISSUE THREAD

**Issue by petersteneteg** [SegaraRai/vcpkg-ports#2]
Hi

Sorry to bother you but I really like your website, your information is so much better then the vcpkg.io

But after coming back from vacation, I noticed that the web site stopped syncing. 

Might be that Github stopped running you actions, since there has not been any pushes for a while. and that might be since 
your port file validator fails to parse https://github.com/microsoft/vcpkg/blob/master/ports/shader-slang/portfile.cmake

it has some #[[ comment ]] and [[ long arg ]] stuff at the end that might mess it up I guess. Maybe you can just disable the validation step for that? Or do you extract info from that file?

Any way, it would be really sad if the site stopped working. Im would be willing to help if possible, but Im a C++ dev mostly...

**Comment by SegaraRai** [comment]
Thanks for catching that! The parser didn't support block comments within arguments, and I had initially relied on the official CMake website, which turned out to be a bit misleading.
I was too lazy to leave it - I've fixed it and it should be good to go for a while.
